package com.oep.hu.pear.users.domain;

public enum Period {
	FIRST_YEAR_PERIOD_A,
	FIRST_YEAR_PERIOD_B,
	FIRST_YEAR_PERIOD_C,
	FIRST_YEAR_PERIOD_D,
	SECOND_YEAR_SEMESTER_ONE,
	SECOND_YEAR_SEMESTER_TWO,
	THIRD_YEAR_SEMESTER_ONE,
	THIRD_YEAR_SEMESTER_TWO,
	FOURTH_YEAR_SEMESTER_ONE,
}
